Nashet/Areas/Admin/Controllers/EmailNotificationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Nashet.Business.Domain;
using Nashet.Business.ViewModels;

namespace Nashet.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class EmailNotificationController : Controller
    {
        private readonly EmailNotificationDomain _EmailNotificationDomain;

        public EmailNotificationController(EmailNotificationDomain emailNotificationDomain )
        {
            _EmailNotificationDomain = emailNotificationDomain ;
        }
        public async Task <IActionResult> ViewEmail()
        {
            var emails = await _EmailNotificationDomain.GetEmailNotification();

            // لو رجع null، حوله لقائمة فاضية
            return View(emails ?? new List<EmailNotificationViewModel>());
        }
        public IActionResult Index()
        {

            return View();
        }

        public async Task<IActionResult> InsertEmail()
        {
            return View();
        }
           [HttpPost]
         [ValidateAntiForgeryToken]
        public async Task<IActionResult> InsertEmail(EmailNotificationViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    int check = await _EmailNotificationDomain.InsertEmail(viewModel);
                    if (check == 1)
                        ViewData["Successful"] = "Successful";
                    else
                        ViewData["Failed"] = "Failed";
                }
                catch
                {
                    ViewData["Failed"] = "Failed";
                }
            }
            return View(viewModel);
        }


    }
}

Nashet/Areas/Admin/Views/EmailNotification/Index.cshtml
@model IEnumerable<EmailNotificationViewModel>

<section class="page_wrap">
    <div class="page_content">
        <div class="block mb-4">
            <div class="block-header border-bottom px-4 py-3">
                <h5 class="m-0">قائمة البريد الإلكتروني</h5>
                <div class="d-flex gap-2">
                    <div class="form-group">
                        <input type="text" class="form-control table__quick_search"
                               placeholder="البحث السريع ...">
                    </div>
                    <a asp-action="InsertEmail" asp-controller="EmailNotification" asp-area="Admin" class="btn btn-primary">إضافة بريد جديد</a>
                </div>
            </div>
            <div class="block-body">
                <table class="table table-hover js-dataTable">
                    <thead>
                        <tr>
                            <th>رقم</th>
                            <th>البريد الإلكتروني</th>
                            <th class="text-end">إجراءات</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null && Model.Any())
                        {
                            foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.EmailNotificationsId</td>
                                    <td>@item.UserEmail</td>
                                    <td class="action_td text-end">
                                        <a href="" class="btn btn-sm btn-primary">عرض</a>
                                        <a href="" class="btn btn-sm btn-success">تعديل</a>
                                        <a href="" class="btn btn-sm btn-danger">حذف</a>
                                    </td>
                                </tr>
                            }
                        }
                        else
                        {
                            <tr>
                                <td colspan="3" class="text-center">لا يوجد بيانات</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

Nashet/Areas/Admin/Views/EmailNotification/InsertEmail.cshtml
@model EmailNotificationViewModel

<section class="page_wrap">
    <div class="page_content">

        <div class="block mb-4">
            <div class="block-header border-bottom px-4 py-4">
                <h5 class="m-0">إضافة بريد إلكتروني</h5>
            </div>
            <div class="block-body py-5">
                <div class="row justify-content-center">
                    <div class="col-md-8">
                        <form asp-action="InsertEmail">
                            <div class="row">
                                <!-- START ITEM -->
                                <div class="col-md-6">
                                    <label asp-for="UserEmail" class="mb-1"></label>
                                    <input asp-for="UserEmail" type="email" class="form-control" placeholder="ادخل البريد الإلكتروني">
                                    <span style="color:red" asp-validation-for="UserEmail"></span>
                                </div><!-- END ITEM -->
                            </div>

                            <div class="d-flex justify-content-end mt-4">
                                <button type="submit" class="btn btn-primary px-5" title="save">حفظ</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section><!-- End Page Wrap -->